### PR TITLE
Update 3x and 2x logo

### PR DESCRIPTION
**Pull request by hesyifei**
Originally the 3x and 2x versions were just scaling up the smaller version and did not actually increase resolution. Now it's clearer.

### CODE REVIEW

**Comment by epicfaace** [comment]
Thanks! How did you get the larger versions?

**Comment by hesyifei** [comment]
> Thanks! How did you get the larger versions?

I just typed "The Stanford Daily" using that Canterbury font. 😂

Here's the PSD: [DailyLogo.psd.zip](https://github.com/TheStanfordDaily/StanfordDaily_Mobile/files/2815176/DailyLogo.psd.zip)

**Comment by epicfaace** [comment]
Cool, can you make a github repo with just graphic assets like that, so we can reuse it in the website / other things if needed?

**Comment by hesyifei** [comment]
> Cool, can you make a github repo with just graphic assets like that, so we can reuse it in the website / other things if needed?

Good idea! https://github.com/TheStanfordDaily/stanforddaily-graphic-assets

**Pull request merged**
